### ISSUE TITLE
characters.pgm got updated

### ISSUE THREAD

**Issue by AbhishekRS4** [BugelNiels/improcc#5]
In the commit  id `bb11734f03908fde6500745102150cbae1b54b89`, the image `characters.pgm` got updated. Previously it was 512 x 512 in dimensions. After update, it became 688 x 688. The fft2D function works only on images with dimensions which is a power of 2. Can you please restore the image? Thanks in advance.

**Comment by BugelNiels** [comment]
Thanks for letting me know. Will do :)

**Comment by BugelNiels** [comment]
One thing to note, not all the images that you will be using the Fast Fourier Transform will have dimensions that are powers of 2, so you will have to find a way around this (with padding) regardless.
